In [1]:
import numpy as np

# Generating 4 log-spaced points from 10^1 to 10^3 (base 10). Useful for logarithmic scales in data analysis.
arr = np.logspace(1, 3, 4, base=10)
print(arr)

# Variation: Base 2 for binary exponents
arr_base2 = np.logspace(0, 3, 4, base=2)
print(arr_base2)

# Edge case: Excluding endpoint
arr_no_end = np.logspace(0, 3, 4, endpoint=False)
print(arr_no_end)

[  10.           46.41588834  215.443469   1000.        ]
[1. 2. 4. 8.]
[  1.           5.62341325  31.6227766  177.827941  ]


In [2]:
import numpy as np

# Filling a 2x3 array with pi, useful for constants in simulations.
arr = np.full((2, 3), np.pi)
print(arr)

# Variation: String fill for non-numeric
arr_str = np.full((2,), 'hello', dtype='U10')
print(arr_str)

# Edge case: Complex numbers
arr_complex = np.full((2,), 1+2j)
print(arr_complex)

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]
['hello' 'hello']
[1.+2.j 1.+2.j]


In [3]:
import numpy as np

# Creating a 3x3 identity matrix, fundamental in linear algebra.
arr = np.eye(3)
print(arr)

# Variation: Offset diagonal (k=1 for superdiagonal)
arr_offset = np.eye(3, k=1)
print(arr_offset)

# Edge case: Non-square (3x4)
arr_rect = np.eye(3, 4)
print(arr_rect)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
